services:
  proxy:
    image: edgd1er/nordvpn-proxy:latest
    restart: unless-stopped
    ports:
      - "1080:1080"
    sysctls:
#      - net.ipv4.conf.all.rp_filter=2 # Loose Reverse Path: https://access.redhat.com/solutions/53031
      - net.ipv6.conf.all.disable_ipv6=1 # disable ipv6
    privileged: true # required for nordvpn client >=3.17.0
    cap_add:
      - NET_ADMIN               # Required
      #- SYS_MODULE              # Required for TECHNOLOGY=NordLynx ?
    environment:
      - TZ=America/Chicago
      - COUNTRY=uk
      - GROUP=P2P
      - CYBER_SEC=off
      - DEBUG=false
      - NORDVPN_LOGIN=<email> #Not required if using secrets
      - NORDVPN_PASS=<pass> #Not required if using secrets
      - ANALYTICS=off # or on, sending anonymous aggregate data: crash reports, OS version, marketing performance, and feature usage data
      - TECHNOLOGY=NordLynx #openvpn or nordlynx
      - PROTOCOL=tcp # or udp (default), useful only when using openvpn. wireguard is udp only.
      - OBFUSCATE=off # or on, obfuscate only available when using openvpn(tcp or udp), hide use of vpn.
      - GENERATE_WIREGUARD_CONF=false #write /etc/wireguard/wg0.conf if true. Will download 56 MB, docker 317 MB of additional disk space will be used.
      - TINYUSER= #optional, enforces authentication over tinyproxy when set with TINYPASS, add authorization with danteuser:${TINYPASS} to socks proxy
      - TINYPASS= #optional, enforces authentication over tinyproxy when set with TINYUSER.
      - DANTE_LOGOUTPUT=file # stdout or file (>/config/log/dante.log)
      - TINYLOGOUTPUT=file # stdout or file (>/config/log/tinyproxy.log)
      - LOG_TO_STDOUT=false # write transmission logs to stdout or to transmission.log

    secrets:
      - NORDVPN_CREDS
      #- NORDVPN_PRIVKEY
      - TINY_CREDS

secrets:
  TINY_CREDS:
    file: ./tiny_creds
  NORDVPN_CREDS:
    file: ./nordvpn_creds
  NORDVPN_PRIVKEY:
    file: ./nordvpn_privkey