name: build multi-arch images

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - '.github/**'
env:
  IMAGE: nordlynx-transmission
  VERSION: "3.14.0"
  TAG: ${{  github.ref_name }}
  REVISION: ${{  github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          install: true
          use: true
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            ${{ secrets.DOCKER_USER }}/${{ env.IMAGE }}
          flavor: |
            latest=${{ startsWith(github.ref, 'refs/heads/main') }}
            #prefix=test,onlatest=true
          tags: |
            type=schedule,pattern=nightly
            type=ref,event=branch,enable=${{ github.event_name != 'schedule' }}
            type=ref,event=tag
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
            TZ=America/Chicago
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ steps.meta.outputs.tags }}
      - name: clean
        if: always() && github.event_name != 'pull_request'
        run: |
          rm -f ${HOME}/.docker/config.json