name: v3 Image Builds
on:
  push:
    branches:
      - main

jobs:
  build-v3-images:
    uses: ./.github/workflows/build-template.yml
    with:
      image-name: edgd1er/nordlynx-transmission
      build-context: '.'
      tbt_version: "3.00"
      version: "3.16.0"
      tag: "v3"
    secrets: inherit

  build-v4-images:
    uses: ./.github/workflows/build-template.yml
    with:
      image-name: edgd1er/nordlynx-transmission
      build-context: '.'
      tbt_version: "4.0.2"
      version: "3.16.0"
      tag: "v4"
    secrets: inherit